config/routes.rb
ServiceProject::Application.routes.draw do

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :requests
      resources :users
      devise_scope :user do
        post 'registrations' => 'registrations#create', :as => 'register'
        post 'sessions' => 'sessions#create', :as => 'login'
        delete 'sessions' => 'sessions#destroy', :as => 'logout'
      end
    end
  end
  devise_for :users
  resources :requests

  root :to => redirect('/requests')

  

end

app/models/request.rb
class Request < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save :ensure_authentication_token
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :token_authenticatable

  def skip_confirmation!
  	self.confirmed_at = Time.now
  end
  
end

app/controllers/api/v1/api_controller.rb
class Api::V1::ApiController < ApplicationController
	respond_to :json

end

app/controllers/api/v1/registrations_controller.rb
module Api
  module V1
    class Api::V1::RegistrationsController < Devise::RegistrationsController
      skip_before_filter :verify_authenticity_token,
                         :if => Proc.new { |c| c.request.format == 'application/json' }

      respond_to :json

      def create
        build_resource(sign_up_params)  
        resource.skip_confirmation!
        if resource.save
          sign_in resource
          render :status => 200,
               :json => { :success => true,
                          :info => "Registered",
                          :data => { :user => resource,
                                     :auth_token => current_user.authentication_token } }
        else
          render :status => :unprocessable_entity,
                 :json => { :success => false,
                            :info => resource.errors,
                            :data => {} }
        end
      end
      def sign_up_params
        params.require(:user).permit(:email, :password, :password_confirmation)
      end
    end
  end
end

app/controllers/api/v1/requests_controller.rb
module Api
  module V1
    class RequestsController < ApplicationController
	skip_before_filter :verify_authenticity_token
      def index
      	respond_to do |format|
      		format.html
        	format.json {render json: Request.all}
        end
      end

      def show
        respond_with Request.find(params[:id])
      end

      def create
    
        @newRequest = Request.create(params[:request])
        respond_to do |format|
        	format.html
        	format.json {render json: @newRequest}
        end

      end

      def update
        respond_with Request.update(params[:id], params[:product])
      end

      def destroy
        respond_with Request.destroy(params[:id])
      end
    end
  end
end

app/controllers/api/v1/sessions_controller.rb
module Api
  module V1
    class SessionsController < Devise::SessionsController
      skip_before_filter :verify_authenticity_token,
                         :if => Proc.new { |c| c.request.format == 'application/json' }

      respond_to :json

      def create
        warden.authenticate!(:scope => resource_name, :recall => "#{controller_path}#failure")
        render :status => 200,
               :json => { :success => true,
                          :info => "Logged in",
                          :data => { :auth_token => current_user.authentication_token } }
      end

      def destroy
        warden.authenticate!(:scope => resource_name, :recall => "#{controller_path}#failure")
        current_user.update_column(:authentication_token, nil)
        render :status => 200,
               :json => { :success => true,
                          :info => "Logged out",
                          :data => {} }
      end

      def failure
        render :status => 401,
               :json => { :success => false,
                          :info => "Login Failed",
                          :data => {} }
      end
    end
  end
end

app/controllers/api/v1/users_controller.rb
module Api
  module V1
    class UsersController < ApplicationController

      def index
      	respond_to do |format|
      		format.html
        	format.json {render json: User.all}
        end
      end

      def show
        respond_with User.find(params[:id])
      end

      def create
        respond_with User.create(params[:product])
      end

      def update
        respond_with User.update(params[:id], params[:product])
      end

      def destroy
        respond_with User.destroy(params[:id])
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  # GET /requests
  # GET /requests.json
  def index
    @requests = Request.all
    respond_to do |format|
      format.html
      format.json { render json: Request.all}
    end
  end

  # GET /requests/1
  # GET /requests/1.json
  def show
  end

  # GET /requests/new
  def new
    @request = Request.new
  end

  # GET /requests/1/edit
  def edit
  end

  # POST /requests
  # POST /requests.json
  def create
    @request = Request.new(request_params)

    respond_to do |format|
      if @request.save
        format.html { redirect_to @request, notice: 'Request was successfully created.' }
        format.json { render action: 'show', status: :created, location: @request }
      else
        format.html { render action: 'new' }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /requests/1
  # PATCH/PUT /requests/1.json
  def update
    respond_to do |format|
      if @request.update(request_params)
        format.html { redirect_to @request, notice: 'Request was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1
  # DELETE /requests/1.json
  def destroy
    @request.destroy
    respond_to do |format|
      format.html { redirect_to requests_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request
      @request = Request.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def request_params
      params.require(:request).permit(:userId, :defecttype, :defectdescription, :defectseverity, :requesteddate, :currentstatus, :requestresolvedate, :paymentamount)
    end
end

app/helpers/api/v1/api_helper.rb
module Api::V1::ApiHelper
end

app/helpers/api/v1/sessions_helper.rb
module Api::V1::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ServiceProject</title>
  <link rel="stylesheet" href="//railsgirls.com/assets/bootstrap.css">
<link rel="stylesheet" href="//railsgirls.com/assets/bootstrap-theme.css">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">The Service Project</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/requests">Requests</a></li>
      </ul>
      <p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
    </div>
  </div>
</nav>

<div class="container">
	<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
  <%= yield %>
</div>
<footer>
  <div class="container">
    Service Project
  </div>
</footer>
<script src="//railsgirls.com/assets/bootstrap.js"></script>
</body>
</html>

app/views/requests/_form.html.erb
<%= form_for(@request) do |f| %>
  <% if @request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@request.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
      <% @request.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :userId %><br>
    <%= f.text_field :userId %>
  </div>
  <div class="field">
    <%= f.label :defecttype %><br>
    <%= f.text_field :defecttype %>
  </div>
  <div class="field">
    <%= f.label :defectdescription %><br>
    <%= f.text_field :defectdescription %>
  </div>
  <div class="field">
    <%= f.label :defectseverity %><br>
    <%= f.text_field :defectseverity %>
  </div>
  <div class="field">
    <%= f.label :requesteddate %><br>
    <%= f.datetime_select :requesteddate %>
  </div>
  <div class="field">
    <%= f.label :currentstatus %><br>
    <%= f.text_field :currentstatus %>
  </div>
  <div class="field">
    <%= f.label :requestresolvedate %><br>
    <%= f.datetime_select :requestresolvedate %>
  </div>
  <div class="field">
    <%= f.label :paymentamount %><br>
    <%= f.number_field :paymentamount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/requests/edit.html.erb
<h1>Editing request</h1>

<%= render 'form' %>

<%= link_to 'Show', @request %> |
<%= link_to 'Back', requests_path %>

app/views/requests/index.html.erb
<h1>Listing requests</h1>

<table>
  <thead>
    <tr>
      <th>Userid</th>
      <th>Defecttype</th>
      <th>Defectdescription</th>
      <th>Defectseverity</th>
      <th>Requesteddate</th>
      <th>Currentstatus</th>
      <th>Requestresolvedate</th>
      <th>Paymentamount</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @requests.each do |request| %>
      <tr>
        <td><%= request.userId %></td>
        <td><%= request.defecttype %></td>
        <td><%= request.defectdescription %></td>
        <td><%= request.defectseverity %></td>
        <td><%= request.requesteddate %></td>
        <td><%= request.currentstatus %></td>
        <td><%= request.requestresolvedate %></td>
        <td><%= request.paymentamount %></td>
        <td><%= link_to 'Show', request %></td>
        <td><%= link_to 'Edit', edit_request_path(request) %></td>
        <td><%= link_to 'Destroy', request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Request', new_request_path %>

app/views/requests/new.html.erb
<h1>New request</h1>

<%= render 'form' %>

<%= link_to 'Back', requests_path %>

app/views/requests/show.html.erb
<p>
  <strong>Userid:</strong>
  <%= @request.userId %>
</p>

<p>
  <strong>Defecttype:</strong>
  <%= @request.defecttype %>
</p>

<p>
  <strong>Defectdescription:</strong>
  <%= @request.defectdescription %>
</p>

<p>
  <strong>Defectseverity:</strong>
  <%= @request.defectseverity %>
</p>

<p>
  <strong>Requesteddate:</strong>
  <%= @request.requesteddate %>
</p>

<p>
  <strong>Currentstatus:</strong>
  <%= @request.currentstatus %>
</p>

<p>
  <strong>Requestresolvedate:</strong>
  <%= @request.requestresolvedate %>
</p>

<p>
  <strong>Paymentamount:</strong>
  <%= @request.paymentamount %>
</p>

<%= link_to 'Edit', edit_request_path(@request) %> |
<%= link_to 'Back', requests_path %>